# GitGuardian configuration for DevTools Desktop
# This file configures how GitGuardian scans this repository for secrets

version: 2

# Configure secret scanning behavior
secret:
  # Exclude test files and documentation from secret scanning
  ignored_paths:
    - 'tests/**/*'
    - '**/*.test.js'
    - '**/*.spec.js'
    - '**/test/**/*'
    - '**/tests/**/*'
    - 'README.md'
    - 'docs/**/*'
    - 'LICENSE'
    - '**/.env.example'
    - '**/.env.template'
    - '**/package.json'
    - '**/package-lock.json'
    - 'assets/**/*'

  # Ignore specific test patterns that are clearly not real secrets
  ignored_matches:
    - name: 'Test data exclusion'
      match: 'Test.*Pass.*123'
    - name: 'Test password patterns'
      match: 'test.*weak'
    - name: 'Test entropy patterns'
      match: 'TestEntropy123!'
    - name: 'Test strong patterns'
      match: 'TestStrong&3'

  # Don't show secrets in output for security
  show_secrets: false

  # Ignore known secrets if they're already tracked
  ignore_known_secrets: true

  # Skip these detectors for test files (if needed)
  # ignored_detectors:
  #   - Generic Password

# General settings
exit_zero: false
verbose: false

# Maximum commits to scan in hooks
max_commits_for_hook: 50

# API settings
allow_self_signed: false
