# GitGuardian pre-commit hook configuration
# Install with: pip install pre-commit
# Run: pre-commit install
#
# This will automatically scan for secrets before each commit

repos:
  - repo: https://github.com/gitguardian/ggshield
    rev: v1.42.0
    hooks:
      - id: ggshield
        language: python
        stages: [commit]
        # Use the configuration from .gitguardian.yaml
